name: coredns
services:
  coredns:
    build:
      context: ./coredns-tailscale
    volumes:
      - ./configurations/coredns-tailscale:/etc/coredns
      - tailscale-socket:/tmp/tailscale
    networks:
      coredns_net:
        ipv4_address: 10.53.53.53
    restart: unless-stopped
    depends_on:
      - tailscale

  tailscale:
    image: tailscale/tailscale:latest
    hostname: coredns
    environment:
      - TS_AUTHKEY=${TS_AUTH_KEY__COREDNS}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ROUTES=10.53.53.0/24
      - TS_ACCEPT_DNS=false
      - TS_SOCKET=/tmp/tailscale/tailscaled.sock
    volumes:
      - tailscale-state:/var/lib/tailscale
      - tailscale-socket:/tmp/tailscale
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    networks:
      coredns_net:
        ipv4_address: 10.53.53.2
    restart: unless-stopped

networks:
  coredns_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.53.53.0/24

volumes:
  tailscale-state:
  tailscale-socket:
